# Generated by Django 3.0 on 2019-12-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0003_auto_20191218_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='returned_data',
            new_name='returned_date',
        ),
    ]
