# Generated by Django 3.0 on 2019-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0004_auto_20191218_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
