# Generated by Django 3.0 on 2019-12-21 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0014_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 17, 8, 57, 381075, tzinfo=utc)),
        ),
    ]
