# Generated by Django 3.0 on 2019-12-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0016_auto_20191221_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrow',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='search',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='view',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='social_network_app.Item'),
        ),
    ]
