# Generated by Django 3.0 on 2020-01-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0018_auto_20200107_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Item'),
        ),
    ]
