rasterizer_cpp: Main.cpp Scene.cpp Camera.cpp Helpers.cpp Color.cpp Matrix4.cpp Model.cpp Rotation.cpp Scaling.cpp tinyxml2.cpp Translation.cpp Triangle.cpp Vec3.cpp Vec4.cpp
	g++ -g -Wall -o rasterizer *.cpp

clean: 
	$(RM) *.ppm