# Generated by Django 3.0 on 2019-12-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
