# Generated by Django 3.0 on 2019-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0002_auto_20191218_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
