# Generated by Django 3.0 on 2019-12-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0005_auto_20191218_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
