# Generated by Django 3.0 on 2019-12-21 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network_app', '0010_auto_20191220_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchrequest',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('sender_user', 'receiver_user')},
        ),
    ]
